
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://10.0.0.245:11434/api/chat
    networks:
      - chatbot-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge 